export const UserDomainRoleOwner = "OWNER"
export const UserDomainRoleAdmin = "ADMIN"
export const UserDomainRoleMember = "MEMBER"

export const UserDomainGeneralSuccessStatusCode = "0000"
export const UserDomainFailedSignUpErrReqBodyValidation = "1001"
export const UserDomainFailedSignUpErrDuplicateDatabaseRecordUserTable = "1002"
export const UserDomainFailedSignInErrReqBodyValidation = "1003"
export const UserDomainFailedSignInErrNoUserFound = "1004"
export const UserDomainFailedSignInErrInvalidPassword = "1005"