export const UserDomainBanApprovalStatusPending = "PENDING"
export const UserDomainBanApprovalStatusBanned = "BANNED"
export const UserDomainBanApprovalStatusRevoked = "REVOKED"

export const UserDomainBanStatusPending = "PENDING"
export const UserDomainBanStatusActive = "ACTIVE"
export const UserDomainBanStatusBanned = "BANNED"

export const UserDomainGenderMale = "MALE"
export const UserDomainGenderFemale = "FEMALE"

export const UserDomainRoleOwner = "OWNER"
export const UserDomainRoleAdmin = "ADMIN"
export const UserDomainRoleMember = "MEMBER"

export const UserDomainGeneralSuccessStatusCode = "0000"
export const UserDomainFailedSignUpErrReqBodyValidation = "1001"
export const UserDomainFailedSignUpErrDuplicateDatabaseRecordUserTable = "1002"
export const UserDomainFailedSignInErrReqBodyValidation = "1003"
export const UserDomainFailedSignInErrNoUserFound = "1004"
export const UserDomainFailedSignInErrInvalidPassword = "1005"
export const UserDomainFailedRequestMemberBanApprovalErrReqBodyValidation = "1025"
export const UserDomainFailedRequestMemberBanApprovalErrUserNotFound = "1026"
export const UserDomainFailedRequestMemberBanApprovalErrBanRequestAlreadyExists = "1027"
export const UserDomainFailedApproveMemberBanRequestErrReqBodyValidation = "1028"